using AdvWorksAPI.EntityLayer;

namespace AdvWorksAPI.RepositoryLayer;

/// <summary>
/// This class creates some fake data for the Customer table.
/// </summary>
public class CustomerRepository
{
  #region Get Method
  /// <summary>
  /// Get all Customer objects
  /// </summary>
  /// <returns>A list of Customer objects</returns>
  public List<Customer> Get()
  {
    return new List<Customer>
    {
      new Customer {
         CustomerID = 1,
         Title = "Mr.",
         FirstName = "Orlando",
         MiddleName = "N.",
         LastName = "Gee",
         CompanyName = "A Bike Store",
         EmailAddress = "orlando0adventure-works.com",
         Phone = "245-555-0173",
         ModifiedDate = Convert.ToDateTime("3/11/2019 2:20:33 PM"),
      },
      new Customer {
         CustomerID = 2,
         Title = "Mr.",
         FirstName = "Keith",
         MiddleName = "asdf",
         LastName = "Harris",
         CompanyName = "Progressive Sports",
         EmailAddress = "keith0adventure-works.com",
         Phone = "170-555-0127",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 3,
         Title = "Ms.",
         FirstName = "Donna",
         MiddleName = null,
         LastName = "Carreras",
         CompanyName = "Advanced Bike Components",
         EmailAddress = "donna0adventure-works.com",
         Phone = "279-555-0130",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 4,
         Title = "Ms.",
         FirstName = "Janet",
         MiddleName = "M.",
         LastName = "Gates",
         CompanyName = "Modular Cycle Systems",
         EmailAddress = "janet1adventure-works.com",
         Phone = "710-555-0173",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 5,
         Title = "Mr.",
         FirstName = "Lucy",
         MiddleName = null,
         LastName = "Harrington",
         CompanyName = "Metropolitan Sports Supply",
         EmailAddress = "lucy0adventure-works.com",
         Phone = "828-555-0186",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 6,
         Title = "Ms.",
         FirstName = "Rosmarie",
         MiddleName = "J.",
         LastName = "Carroll",
         CompanyName = "Aerobic Exercise Company",
         EmailAddress = "rosmarie0adventure-works.com",
         Phone = "244-555-0112",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 7,
         Title = "Mr.",
         FirstName = "Dominic",
         MiddleName = "P.",
         LastName = "Gash",
         CompanyName = "Associated Bikes",
         EmailAddress = "dominic0adventure-works.com",
         Phone = "192-555-0173",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 10,
         Title = "Ms.",
         FirstName = "Kathleen",
         MiddleName = "M.",
         LastName = "Garza",
         CompanyName = "Rural Cycle Emporium",
         EmailAddress = "kathleen0adventure-works.com",
         Phone = "150-555-0127",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 11,
         Title = "Ms.",
         FirstName = "Katherine",
         MiddleName = null,
         LastName = "Harding",
         CompanyName = "Sharp Bikes",
         EmailAddress = "katherine0adventure-works.com",
         Phone = "926-555-0159",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 12,
         Title = "Mr.",
         FirstName = "Johnny",
         MiddleName = "A.",
         LastName = "Caprio",
         CompanyName = "Bikes and Motorbikes",
         EmailAddress = "johnny0adventure-works.com",
         Phone = "112-555-0191",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 16,
         Title = "Mr.",
         FirstName = "Christopher",
         MiddleName = "R.",
         LastName = "Beck",
         CompanyName = "Bulk Discount Store",
         EmailAddress = "christopher1adventure-works.com",
         Phone = "1 (11) 500 555-0132",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 18,
         Title = "Mr.",
         FirstName = "David",
         MiddleName = "J.",
         LastName = "Liu",
         CompanyName = "Catalog Store",
         EmailAddress = "david20adventure-works.com",
         Phone = "440-555-0132",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 19,
         Title = "Mr.",
         FirstName = "John",
         MiddleName = "A.",
         LastName = "Beaver",
         CompanyName = "Center Cycle Shop",
         EmailAddress = "john8adventure-works.com",
         Phone = "521-555-0195",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 20,
         Title = "Ms.",
         FirstName = "Jean",
         MiddleName = "P.",
         LastName = "Handley",
         CompanyName = "Central Discount Store",
         EmailAddress = "jean1adventure-works.com",
         Phone = "582-555-0113",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 21,
         Title = null,
         FirstName = "Jinghao",
         MiddleName = null,
         LastName = "Liu",
         CompanyName = "Chic Department Stores",
         EmailAddress = "jinghao1adventure-works.com",
         Phone = "928-555-0116",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 22,
         Title = "Ms.",
         FirstName = "Linda",
         MiddleName = "E.",
         LastName = "Burnett",
         CompanyName = "Travel Systems",
         EmailAddress = "linda4adventure-works.com",
         Phone = "121-555-0121",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 23,
         Title = "Mr.",
         FirstName = "Kerim",
         MiddleName = null,
         LastName = "Hanif",
         CompanyName = "Bike World",
         EmailAddress = "kerim0adventure-works.com",
         Phone = "216-555-0122",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 24,
         Title = "Mr.",
         FirstName = "Kevin",
         MiddleName = null,
         LastName = "Liu",
         CompanyName = "Eastside Department Store",
         EmailAddress = "kevin5adventure-works.com",
         Phone = "926-555-0164",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 25,
         Title = "Mr.",
         FirstName = "Donald",
         MiddleName = "L.",
         LastName = "Blanton",
         CompanyName = "Coalition Bike Company",
         EmailAddress = "donald0adventure-works.com",
         Phone = "357-555-0161",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 28,
         Title = "Ms.",
         FirstName = "Jackie",
         MiddleName = "E.",
         LastName = "Blackwell",
         CompanyName = "Commuter Bicycle Store",
         EmailAddress = "jackie0adventure-works.com",
         Phone = "972-555-0163",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 29,
         Title = "Mr.",
         FirstName = "Bryan",
         MiddleName = null,
         LastName = "Hamilton",
         CompanyName = "Cross-Country Riding Supplies",
         EmailAddress = "bryan2adventure-works.com",
         Phone = "344-555-0144",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 30,
         Title = "Mr.",
         FirstName = "Todd",
         MiddleName = "R.",
         LastName = "Logan",
         CompanyName = "Cycle Merchants",
         EmailAddress = "todd0adventure-works.com",
         Phone = "783-555-0110",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 34,
         Title = "Ms.",
         FirstName = "Barbara",
         MiddleName = "J.",
         LastName = "German",
         CompanyName = "Cycles Wholesaler & Mfg.",
         EmailAddress = "barbara4adventure-works.com",
         Phone = "1 (11) 500 555-0181",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 37,
         Title = "Mr.",
         FirstName = "Jim",
         MiddleName = null,
         LastName = "Geist",
         CompanyName = "Two Bike Shops",
         EmailAddress = "jim1adventure-works.com",
         Phone = "724-555-0161",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 38,
         Title = "Ms.",
         FirstName = "Betty",
         MiddleName = "M.",
         LastName = "Haines",
         CompanyName = "Finer Mart",
         EmailAddress = "betty0adventure-works.com",
         Phone = "867-555-0114",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 39,
         Title = "Ms.",
         FirstName = "Sharon",
         MiddleName = "J.",
         LastName = "Looney",
         CompanyName = "Fitness Hotel",
         EmailAddress = "sharon2adventure-works.com",
         Phone = "377-555-0132",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 40,
         Title = "Mr.",
         FirstName = "Darren",
         MiddleName = null,
         LastName = "Gehring",
         CompanyName = "Journey Sporting Goods",
         EmailAddress = "darren0adventure-works.com",
         Phone = "417-555-0182",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 41,
         Title = "Ms.",
         FirstName = "Erin",
         MiddleName = "M.",
         LastName = "Hagens",
         CompanyName = "Distant Inn",
         EmailAddress = "erin1adventure-works.com",
         Phone = "244-555-0127",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 42,
         Title = "Mr.",
         FirstName = "Jeremy",
         MiddleName = null,
         LastName = "Los",
         CompanyName = "Healthy Activity Store",
         EmailAddress = "jeremy0adventure-works.com",
         Phone = "911-555-0165",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 43,
         Title = "Ms.",
         FirstName = "Elsa",
         MiddleName = null,
         LastName = "Leavitt",
         CompanyName = "Frugal Bike Shop",
         EmailAddress = "elsa0adventure-works.com",
         Phone = "482-555-0174",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 46,
         Title = "Mr.",
         FirstName = "David",
         MiddleName = "O",
         LastName = "Lawrence",
         CompanyName = "Gear-Shift Bikes Limited",
         EmailAddress = "david19adventure-works.com",
         Phone = "653-555-0159",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 47,
         Title = "Ms.",
         FirstName = "Hattie",
         MiddleName = "J.",
         LastName = "Haemon",
         CompanyName = "Greater Bike Store",
         EmailAddress = "hattie0adventure-works.com",
         Phone = "141-555-0172",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 48,
         Title = "Ms.",
         FirstName = "Anita",
         MiddleName = "R.",
         LastName = "Lucerne",
         CompanyName = "Grand Industries",
         EmailAddress = "anita0adventure-works.com",
         Phone = "164-555-0118",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 52,
         Title = "Ms.",
         FirstName = "Rebecca",
         MiddleName = null,
         LastName = "Laszlo",
         CompanyName = "Instruments and Parts Company",
         EmailAddress = "rebecca2adventure-works.com",
         Phone = "1 (11) 500 555-0155",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 55,
         Title = "Mr.",
         FirstName = "Eric",
         MiddleName = null,
         LastName = "Lang",
         CompanyName = "Kickstands and Accessories Company",
         EmailAddress = "eric6adventure-works.com",
         Phone = "932-555-0163",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 56,
         Title = "Mr.",
         FirstName = "Brian",
         MiddleName = null,
         LastName = "Groth",
         CompanyName = "Latest Accessories Sales",
         EmailAddress = "brian5adventure-works.com",
         Phone = "461-555-0118",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 57,
         Title = "Ms.",
         FirstName = "Judy",
         MiddleName = "R.",
         LastName = "Lundahl",
         CompanyName = "Leading Sales & Repair",
         EmailAddress = "judy1adventure-works.com",
         Phone = "260-555-0130",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 58,
         Title = "Mr.",
         FirstName = "Peter",
         MiddleName = null,
         LastName = "Kurniawan",
         CompanyName = "Largest Bike Store",
         EmailAddress = "peter4adventure-works.com",
         Phone = "436-555-0160",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 59,
         Title = "Mr.",
         FirstName = "Douglas",
         MiddleName = null,
         LastName = "Groncki",
         CompanyName = "Locks Company",
         EmailAddress = "douglas2adventure-works.com",
         Phone = "385-555-0140",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 60,
         Title = "Mr.",
         FirstName = "Sean",
         MiddleName = "J.",
         LastName = "Lunt",
         CompanyName = "Main Bicycle Services",
         EmailAddress = "sean4adventure-works.com",
         Phone = "183-555-0111",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 61,
         Title = "Mr.",
         FirstName = "Jeffrey",
         MiddleName = null,
         LastName = "Kurtz",
         CompanyName = "Many Bikes Store",
         EmailAddress = "jeffrey3adventure-works.com",
         Phone = "452-555-0179",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 64,
         Title = "Mr.",
         FirstName = "Vamsi",
         MiddleName = null,
         LastName = "Kuppa",
         CompanyName = "Metal Clearing House",
         EmailAddress = "vamsi1adventure-works.com",
         Phone = "290-555-0196",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 65,
         Title = "Ms.",
         FirstName = "Jane",
         MiddleName = "P.",
         LastName = "Greer",
         CompanyName = "Metro Manufacturing",
         EmailAddress = "jane2adventure-works.com",
         Phone = "737-555-0163",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 66,
         Title = "Mr.",
         FirstName = "Alexander",
         MiddleName = "J.",
         LastName = "Deborde",
         CompanyName = "Neighborhood Store",
         EmailAddress = "alexander1adventure-works.com",
         Phone = "394-555-0176",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 70,
         Title = "Mr.",
         FirstName = "Deepak",
         MiddleName = null,
         LastName = "Kumar",
         CompanyName = "Outdoor Aerobic Systems Company",
         EmailAddress = "deepak0adventure-works.com",
         Phone = "1 (11) 500 555-0122",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 73,
         Title = "Ms.",
         FirstName = "Margaret",
         MiddleName = "T.",
         LastName = "Krupka",
         CompanyName = "Outdoor Sports Supply",
         EmailAddress = "margaret1adventure-works.com",
         Phone = "107-555-0132",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 74,
         Title = "Mr.",
         FirstName = "Christopher",
         MiddleName = "M.",
         LastName = "Bright",
         CompanyName = "Parcel Express Delivery Service",
         EmailAddress = "christopher2adventure-works.com",
         Phone = "162-555-0166",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 75,
         Title = "Ms.",
         FirstName = "Aidan",
         MiddleName = null,
         LastName = "Delaney",
         CompanyName = "Paint Supply",
         EmailAddress = "aidan0adventure-works.com",
         Phone = "358-555-0188",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 76,
         Title = "Mr.",
         FirstName = "James",
         MiddleName = "J.",
         LastName = "Krow",
         CompanyName = "Out-of-the-Way Hotels",
         EmailAddress = "james11adventure-works.com",
         Phone = "265-555-0190",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 77,
         Title = "Mr.",
         FirstName = "Michael",
         MiddleName = null,
         LastName = "Brundage",
         CompanyName = "Mechanical Products Ltd.",
         EmailAddress = "michael13adventure-works.com",
         Phone = "128-555-0148",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 78,
         Title = "Mr.",
         FirstName = "Stefan",
         MiddleName = null,
         LastName = "Delmarco",
         CompanyName = "Preferred Bikes",
         EmailAddress = "stefan0adventure-works.com",
         Phone = "819-555-0186",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 79,
         Title = "Mr.",
         FirstName = "Mitch",
         MiddleName = null,
         LastName = "Kennedy",
         CompanyName = "Reasonable Bicycle Sales",
         EmailAddress = "mitch0adventure-works.com",
         Phone = "996-555-0192",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 82,
         Title = "Mr.",
         FirstName = "James",
         MiddleName = "D.",
         LastName = "Kramer",
         CompanyName = "Refined Department Stores",
         EmailAddress = "james10adventure-works.com",
         Phone = "814-555-0130",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 83,
         Title = "Mr.",
         FirstName = "Eric",
         MiddleName = "J.",
         LastName = "Brumfield",
         CompanyName = "Requisite Part Supply",
         EmailAddress = "eric3adventure-works.com",
         Phone = "644-555-0114",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 84,
         Title = "Ms.",
         FirstName = "Della",
         MiddleName = "F.",
         LastName = "Demott Jr",
         CompanyName = "Rewarding Activities Company",
         EmailAddress = "della0adventure-works.com",
         Phone = "752-555-0185",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 88,
         Title = "Ms.",
         FirstName = "Pamala",
         MiddleName = "M.",
         LastName = "Kotc",
         CompanyName = "Closest Bicycle Store",
         EmailAddress = "pamala0adventure-works.com",
         Phone = "1 (11) 500 555-0173",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 91,
         Title = "Ms.",
         FirstName = "Joy",
         MiddleName = "R.",
         LastName = "Koski",
         CompanyName = "Scooters and Bikes Store",
         EmailAddress = "joy0adventure-works.com",
         Phone = "810-555-0198",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 92,
         Title = "Ms.",
         FirstName = "Jovita",
         MiddleName = "A.",
         LastName = "Carmody",
         CompanyName = "Sports Commodities",
         EmailAddress = "jovita0adventure-works.com",
         Phone = "646-555-0137",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 93,
         Title = "Mr.",
         FirstName = "Prashanth",
         MiddleName = null,
         LastName = "Desai",
         CompanyName = "Stationary Bikes and Stands",
         EmailAddress = "prashanth0adventure-works.com",
         Phone = "138-555-0156",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 94,
         Title = "Mr.",
         FirstName = "Scott",
         MiddleName = null,
         LastName = "Konersmann",
         CompanyName = "Specialty Sports Store",
         EmailAddress = "scott6adventure-works.com",
         Phone = "556-555-0192",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 95,
         Title = "Ms.",
         FirstName = "Jane",
         MiddleName = "N.",
         LastName = "Carmichael",
         CompanyName = "Rural Department Store",
         EmailAddress = "jane0adventure-works.com",
         Phone = "716-555-0167",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 96,
         Title = "Ms.",
         FirstName = "Bonnie",
         MiddleName = "B.",
         LastName = "Lepro",
         CompanyName = "More Bikes!",
         EmailAddress = "bonnie2adventure-works.com",
         Phone = "354-555-0130",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 97,
         Title = "Mr.",
         FirstName = "Eugene",
         MiddleName = null,
         LastName = "Kogan",
         CompanyName = "Mountain Bike Center",
         EmailAddress = "eugene2adventure-works.com",
         Phone = "136-555-0134",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM")
      }
      }
    };
  }
  #endregion

  #region Get Method
  /// <summary>
  /// Get a single Customer object
  /// </summary>
  /// <param name="id">The value to locate</param>
  /// <returns>A valid Customer object object, or null if not found</returns>
  public Customer? Get(int id) {
    return Get().Where(row => row.CustomerID == id).FirstOrDefault();
  }
  #endregion
}